### ISSUE TITLE
Physiks and Explosions bugging in 1.16.3

### ISSUE THREAD

**Issue by HollydaysJolo** [einTosti/BuildSystem#1]
**Describe the bug**
Physiks and Explosions are bugging on Spigot 1.16.3 (Lava and Water are not Flowing)

**To Reproduce**
1. Setup an Spigot 1.16.3 Minecraft server.
2. Load Buildsystem on it.
3. Try to Explode something or try to stop Lava.
4. Try to change the Settings.
5. See that it will not work.

**Expected behavior**
That TNT or Tnt -Minecarts explode. That Water flows

**Screenshots**
To much to show, and hard to show

**Comment by einTosti** [comment]
What do you mean with 3? Do you stop lava with e.g. a block?
And do you change the settings with /physics? In that case the physics should be deactivated, no?

**Comment by HollydaysJolo** [comment]
When I place a bucket full of water in the world. And it Spreads with Physiks off over /physics or the menu then the Water will not there like planed. When I do the same thing with physics on The Water will Spread and will not leave the Positions where it was Spawned when i place a block into the Block where its standing.

Here some picktures to show. These are two in the 
respective mode  plantet water sources

![2020-10-20_20 01 24](https://user-images.githubusercontent.com/65872875/96626087-5071bb00-130f-11eb-8706-59140e56d281.png)
![2020-10-20_20 01 37](https://user-images.githubusercontent.com/65872875/96626091-51a2e800-130f-11eb-8c49-7736480411f2.png)


TNT will not explode in any mode. 


P.S. if you leav Lava the option to Spread on time it will not Spread when you take away the source. If you wait until one spread more it stands there still.

**Comment by einTosti** [comment]
I know your error occurs in `1.16.3`, but everything works find in `1.8`. However, the code is exactly the same for all versions. That's why I must do a more detailed analysis

**Comment by einTosti** [comment]
Can you confirm that this error still occurs in `1.16.4`?`
