### ISSUE TITLE
Cant Import Worlds on Normal Servers without the Plugin 

### ISSUE THREAD

**Issue by BIGNITOR** [einTosti/BuildSystem#11]
Hey i Got a Problem with my Plugin if i want to Import my builded world from my buildServer (with the Plugin) To my Network it Generates a New World instead of Loading my World it is a Void World with only some things (Bedwars) So its not even much to load

I Stopped my Server replaces it with world and started it and it doesnt work and the game creates a new random world.

I even tried it with Importing my World into  Singleplayer and it Generates a New world too

I have Spigot 1.8.9
and the latest Version of the Plugin.

**Comment by einTosti** [comment]
So are you saying that if you 

1. Generate a **void world** with `BuildSystem`
2. Copy the world to a server without the plugin

that the world doesn't stay as a void world?

**Comment by BIGNITOR** [comment]
Yes My Void world Changes into a new Generated World after i put it on a Different Server this is very weird

**Comment by einTosti** [comment]
Sadly there is not much I can do about the issue. That's just the way Spigot works. Once the custom world generator ist remove (in this case `BuildSystem`), then the world is generated with the normal generator

**Comment by BIGNITOR** [comment]
And How Can i import the Map? Do i need to but Build System on every Server to Import it?

**Comment by einTosti** [comment]
Sadly, yes. Or use Multiverse and use their Void-Generator

**Comment by BIGNITOR** [comment]
Okay Thank you for Explaining
