### ISSUE TITLE
BuildSystem bug with noai, superpickaxe and br

### ISSUE THREAD

**Issue by Birsenberg** [einTosti/BuildSystem#24]
**Describe the bug**
1.NoAI settings not work on last 1.17.1 paper core.
2.BuildSystem does not block worldeditcommands like /sp and br

**Server information:**
 - Server version 1.17.1 paper core
 - Plugin version 2.16.1

**Comment by EinJOJO** [comment]
Hey!

I tested it and I could not find a problem. 

### MobAI bug:
**Test:**
environment: 
> Tester had _OP_, 
> Server Version: Paper-1.17.1-164
> Plugins: FAWE and Buildsystem

test-sequence: 
> Created a new World => disabled Mob-AI => spawned mobs => Saw that they had no AI

Annotation: Mob-AI does not affect mobs, that are already in the world.
Result: =>Everything works fine



### Worledit commands
Test 1:

environment: 
> Tester had buildsystem.gamemode, worldedit.* 
> Server Version: Paper-1.17.1-164
> Plugins: FAWE and Buildsystem

test-sequence: 
> Created a new World => enabled Builders => use /sp => get error message.

Works fine.



Test 2: 
environment: 
> Tester had OP, and _buildsystem.bypass.builders = false_

test-sequence: 
> same as above.

Tester could use worldedit.



Test 3:
environment: 
> Tester had buildsystem.* and _buildsystem.bypass.builders = false_

test-sequence: 
> same as above.

Tester could also use worldedit


Conclusion: I need to test this more: 

Please send me your permissions file.

**Comment by einTosti** [comment]
Do you have the one (or more) of the following permissions?
- `buildsystem.admin`
- `buildsystem.bypass.archive`

If so, then you can use WorldEdit commands, even if you are not a builder

**Comment by einTosti** [comment]
**NoAI**:
As @EinJOJO previously stated:
> ### MobAI bug:
> **Test:**
> environment:
> 
> > Tester had _OP_,
> > Server Version: Paper-1.17.1-164
> > Plugins: FAWE and Buildsystem
> 
> test-sequence:
> 
> > Created a new World => disabled Mob-AI => spawned mobs => Saw that they had no AI
> 
> Annotation: Mob-AI does not affect mobs, that are already in the world.
> Result: =>Everything works fine
 the bug could not be replicated. 

If it still occurs please open a new issue **with a video demonstrating the problem**.

**WorldEdit:**
The issue with the WorldEdit commands should be fixed. If any more (important ones) are missing, please open a new issue.
