### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by Luisitohh** [einTosti/BuildSystem#30]
I would like you to add new commands and functions to BuildSystem Plugin

* /SetWarp (byworld) for world creators to define places that those who enter that world can visit
* /SetHome (byplayer in own world) so that the world creator does not lose his localization project
* /SetSpawn (for Main World spawn) to put a main Lobby where all the players enter and if they want to return
/warp
/home
/spawn
/tpworld (for teleport to other worlds) to go to the external worlds loaded
/world import (for import worlds) to import external worlds
Permission and commands for private world
Like
/w add add permissions so that players can only build or modify the world when the owner is online
/w trust add permissions to a trusted player who can build or modify the world even if the owner is not on the server
/w remove remove permission add
/w untrust remove trust
/w use so that players outside the world can use levers or pressure plate, chests, etc.

and to be able to deactivate some invoices of your plugin like generations of normal worlds or nether etc

if u want, u can add gui for this facture and add SQL if u want

Im _blackFx (buyer)
if u need help, write me to my discord: Luisito#7552

**Comment by EinJOJO** [comment]
/SetWarp
/warp
/home

Are not essential for the buildsystem. In this case you should use a home/warp plugin.

/spawn [set/remove] || set a global spawn
/worlds setSpawn || set world spawn 
/worlds import <Name> || to import worlds

/worlds gives you a overview about all commands

**Comment by einTosti** [comment]
Everything that @EinJOJO stated, is correct. Most of the features are already implemented.

>   /tpworld (for teleport to other worlds) to go to the external worlds loaded

>   /w add add permissions so that players can only build or modify the world when the owner is online
>   /w trust add permissions to a trusted player who can build or modify the world even if the owner is not on the server
>   /w remove remove permission add
>   /w untrust remove trust
>   /w use so that players outside the world can use levers or pressure plate, chests, etc.

**Check out builders:**

- When a world has builders enabled (private worlds by default, public worlds after being enabled), only these players can place and destroy blocks
- A list of a world's builder can be seen in the world editor or with /worlds builders  (Permission: `worlds.builders`) 
- Add a builder in the world editor or with `/worlds addBuilder`  (Permission: `worlds.addbuilder`)
- Remove a builder in the world editor or with `/worlds removeBuilder`  (Permission: _worlds.removebuilder_)
- Only the world creator can add or remove builders! (Set the creator with `/worlds setCreator` ) 
- Can be disabled in the config (_block-world-edit-non-builder_)

> if u want, u can [...] add SQL if u want
What would you need SQL for?
