### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by PlayGameDEV** [einTosti/BuildSystem#31]
**Is your feature request related to a problem? Please describe.**
Das Problem ist, wenn ich das Plugin Updaten möchte weiß ich nie welche Version ich gerade auf dem Server habe.

**Describe the solution you'd like**
Es wäre schön wenn man im Download auf SpigotMC auch in den Dateinamen die Versionsnummer schreibt.

**Describe alternatives you've considered**
Mag keine Alternativen :p

**Additional context**
Denke es wirds nicht benötigt.

**Comment by einTosti** [comment]
Kann ich ab dem nächsten Update hinzufügen.

Allerdings kann man auch ganz einfach `/version BuildSystem` verwenden :)

**Comment by einTosti** [comment]
Wurde intern implementiert
