### ISSUE TITLE
ArmorStand armor disappears when importing world

### ISSUE THREAD

**Issue by chaosmann09** [einTosti/BuildSystem#34]
**Describe the bug**
If I import Worlds then the clothes are gone with the armor stands, so the leather. This is not the case with other plugins like MV. 

**Screenshots**
https://prnt.sc/1xlxnbo

**Server information:**
- Minecraft Version 1.16.5
 - Server version [Spigot,]
 - Plugin version the latest

**Comment by einTosti** [comment]
@chaosmann09 have you read my message?

**Comment by einTosti** [comment]
I am still unable to reproduce the issue. If the error persists in the latest (plugin) version, please open a new report
