### ISSUE TITLE
New Feature 

### ISSUE THREAD

**Issue by TWME-TW** [einTosti/BuildSystem#48]
Add a member management function like __Hypixel housing__

(GUI)

(~~Google translate~~

**Comment by einTosti** [comment]
Already exists -> **Builders**

- When a world has builders enabled (private worlds by default, public worlds after being enabled), only these players can place and destroy blocks
- A list of a world's builder can be seen in the world editor or with `/worlds builders` (Permission: `worlds.builders`) 
- Add a builder in the world editor or with `/worlds addBuilder` (Permission: `worlds.addbuilder`)
- Remove a builder in the world editor or with `/worlds removeBuilder` (Permission: `worlds.removebuilder`)
- Only the world creator can add or remove builders! (Set the creator with `/worlds setCreator`)

**Comment by TWME-TW** [comment]
👍🙂
