### ISSUE TITLE
[Bug] Connected texture issue in 1.14.4 servers with physics (spigot, and paperspigot)

### ISSUE THREAD

**Issue by MrMathias154** [einTosti/BuildSystem#5]
**Describe the bug**
When physics in world menu is deactivated, the connection between object are not made, like glass pane or stairs, or any other connected textures

**To Reproduce**
1. Go into the navigator
2. World navigator
3. Edit the word
4. Disable Block Physics

**Expected behavior**
normally disable physics not connected textures

**Screenshots**
[video]
https://www.dailymotion.com/video/x7xniyj

**Server information:**
 - Minecraft version: 1.14.4
 - Server version Spigot and PaperSpigot - 1.14.4
 - Plugin version 2.14.4 (From spigot and ChunkFactory)

**Comment by einTosti** [comment]
I actually don't know if this bug can be fixed. According to the video (if I can see correctly) only one player is affected. I'm wondering if this is a client side issue

**Comment by EinJOJO** [comment]
This isn't a bug - It's a feature xD

**Comment by einTosti** [comment]
> I actually don't know if this bug can be fixed. According to the video (if I can see correctly) only one player is affected. I'm wondering if this is a client side issue

As I still think this is the issue, I will close this. Maybe try out newer versions, perhaps it has been fixed
