### ISSUE TITLE
New Feature! Luckperms Context

### ISSUE THREAD

**Issue by TWME-TW** [einTosti/BuildSystem#56]
I think supporting `Luckperm's Context` is a very powerful feature.

https://luckperms.net/wiki/Context

Let Luckperms detect if a player is a Builder or Creator or just a visitor, and if so, give the player specific permissions~

Or is there a better/existing way?

**Comment by einTosti** [comment]
That’s a good idea.
I think I would implement it as `role` (Name might vary) being able to take the values `creator`, `builder` and `visitor`

**Comment by TWME-TW** [comment]
> Is #57 what you had in mind?

i think yes

**Comment by einTosti** [comment]
Implemented in #57
