### ISSUE TITLE
Can't open the Private Worlds Menu (NullPointerException: null)

### ISSUE THREAD

**Issue by PbtMaster** [einTosti/BuildSystem#6]
**Describe the bug**
When all my builders and me included click the Private Worlds head it does not work, and prints this error in the Console: 
Could not pass event InventoryClickEvent to BuildSystem v2.14.5 java.lang.NullPointerException: null

**To Reproduce**
1. Go to the Navigator
2. Click on the Private Worlds Head
3. See error in Console

**Server information:**
 - Minecraft version: [1.15.2]
 - Server version [Paper]
 - Plugin version [2.14.5]

**Comment by einTosti** [comment]
Can you please send your whole error message as I am unable to reproduce the issue?

**Comment by PbtMaster** [comment]
that's the whole error

**Comment by PbtMaster** [comment]
there's no more error message

**Comment by PbtMaster** [comment]
but the error only happens on changing normal world to private, and the version is not 1.16 it's 1.15.2, it does not happen when there's no worlds in private

**Comment by einTosti** [comment]
Oops my bad. Changed it to 1.15 and I'll try it out again later.

Concerning the error: I mean that it should say `java.lang.NullPointerException: null` and then a lot behind that.

**Comment by PbtMaster** [comment]
i'm sorry, but it does not say anything else

**Comment by einTosti** [comment]
Can you then send me you `worlds.yml` file, please

**Comment by PbtMaster** [comment]
ok, i'll send it to you on private on discord

**Comment by PbtMaster** [comment]
and i tell you again, they are setting their world in private, with an already public world, and it gives this error, and the inventory does not open

**Comment by einTosti** [comment]
Can you please send me your whole LOG and not just the error?

**Comment by PbtMaster** [comment]
Sorry for making you wait, i was testing it

**Comment by PbtMaster** [comment]
after testing for a while i found that it was my problem, i'm sorry, it works great

**Comment by einTosti** [comment]
Alright, good to hear
