### ISSUE TITLE
World Display Name

### ISSUE THREAD

**Issue by TWME-TW** [einTosti/BuildSystem#69]
Idea from my co-admin:
Like Multiverse-core

World Display Name ≠ World Folder Name

NewWorldName : 'member-%player%-%id%-%WorldNick%'

NewWorldDisplayName:
   display: "name"

**Comment by einTosti** [comment]
It's already possible to change the name of a world's item in the GUI

![Screenshot 2022-02-15 at 15 17 00](https://user-images.githubusercontent.com/29168243/154080268-2140d53e-a08d-47bd-9149-56dfa38a2b0b.png)
becomes
![Screenshot 2022-02-15 at 15 20 05](https://user-images.githubusercontent.com/29168243/154080460-fd787bf7-a549-4184-b725-e2b194c07b88.png)

Or do you mean something else?
