### ISSUE TITLE
Block Place Range

### ISSUE THREAD

**Issue by EinHonigtee** [einTosti/BuildSystem#7]
Ein Feature bei den man einstellen kann in welcher entfernung man blöcke abbauen/platzieren kann.
Vllt ist sowas ja möglich.

**Comment by einTosti** [comment]
Das einzige was möglich wäre, wäre die Reichweite zu verkürzen, was meiner Meinung nach keinen Sinn ergibt. Eine Verlängerung ist leider nicht möglich
