### ISSUE TITLE
Navigator does not stay in inventory when „Keep Navigator“ is enabled

### ISSUE THREAD

**Issue by iamh4ppii** [einTosti/BuildSystem#74]
The Navigator aren´t stay in inventory, if the setting "keep inventory" is aktivated and you delete your inventory.

**Comment by einTosti** [comment]
Need the following information:
- Server Version
- Plugin version
- Error log (if any)
- Steps to reproduce, i.e. How is the inventory cleared

**Comment by iamh4ppii** [comment]
Server Version 1.18.1 
Plugin Version newest
no log
if you clicked on the delete button in creativ
