### ISSUE TITLE
Random letters appearing after server restart in messages.yml

### ISSUE THREAD

**Issue by Antimoxs** [einTosti/BuildSystem#77]
After restarting the server, the plugin adds weird letters and symbols to some strings inside the messages.yml file

![grafik](https://user-images.githubusercontent.com/42115621/156459998-25b69465-8cb7-47ad-960e-51b0edbea475.png)

**Comment by einTosti** [comment]
Need the following information:
- Server Version
- Plugin version
- Error log (if any)
- Steps to reproduce

**Comment by EinJOJO** [comment]
Do you run the server on windows?

**Comment by Antimoxs** [comment]
Server: spigot 1.8.9
plugin v: 2.17.2-dev
error log: none
steps: 
 1. /stop (console)
 2. start server

**Comment by einTosti** [comment]
Does the error still occur when adding `-Dfile.encoding=UTF-8` to your start command? (after `java`)
