### ISSUE TITLE
Error when importing an already existing world

### ISSUE THREAD

**Issue by manupel** [einTosti/BuildSystem#8]
**Describe the bug**
As soon as a new world is to be imported, which is already in the server directory, I get the following error message:

"An internal error occurred while attempting to perform this command"

**To Reproduce**
/worlds import [world]

**Expected behavior**
I assume, of course, that a world can be imported without any problems.

**Screenshots**
https://prnt.sc/10rkzm5
https://www.codepile.net/pile/0yXXZVyK

**Server information:**
 - Minecraft version: 1.8.8
 - Server version: Paper
 - Plugin version: latest

**Additional context**
I don't know if this is not also due to my server. Maybe you can help me?

**Comment by einTosti** [comment]
The issue lies with the world "world_the_end".
Was it by chance created in a newer version than 1.8? Also try removing the world and running the command again

**Comment by manupel** [comment]
The map "world_the_end" does not even exist in the server directory.

**Comment by einTosti** [comment]
What is the default world then?

**Comment by manupel** [comment]
The default world is "world". I have already deleted the other worlds (Nether and End).

**Comment by einTosti** [comment]
Those worlds can't be deleted, the server will always try and recreate them.
Try stopping and starting the server again and without doing anything else, rerun the command

**Comment by manupel** [comment]
I stopped the server and started it again. The worlds "world_nether" and "world_the_end" are now back. Then I executed the command "/worlds import Lobby" and got again the error message as described above.

Console: https://www.codepile.net/pile/mAebJnxG

**Comment by einTosti** [comment]
Does the plugin have enough permissions to copy system files?

**Comment by manupel** [comment]
Actually, the rights should all be correct.

I get the following warning when reloading the server:

https://www.codepile.net/pile/am0A2Okb

Does this have anything to do with it?

**Comment by manupel** [comment]
I would be happy to show you this live, possibly via Discord with screen transmission?

**Comment by einTosti** [comment]
I'm very busy at the moment so now isn't really a good time. 
Try deleting the session.lock

**Comment by manupel** [comment]
I already have, but it still doesn't work.

**Comment by einTosti** [comment]
I honestly have no idea what the issue is... maybe try this https://gaming.stackexchange.com/questions/184226/how-do-i-fix-the-failed-to-check-session-lock-for-world-error

**Comment by manupel** [comment]
I tried it once with Multiverse-Core as a test, but I get the same error there. So it's not because of your plugin.

Sorry - I didn't know that!

**Comment by manupel** [comment]
The problem is fixed. I uploaded the worlds with the wrong user, so the rights were not sufficient.

Many thanks for your help!
