### ISSUE TITLE
Custom World Generator world creation support

### ISSUE THREAD

**Issue by galexrt** [einTosti/BuildSystem#9]
**Is your feature request related to a problem? Please describe.**

Currently there is no easy way to create a new world that uses a Custom World Generator from the World Navigator. It would be cool if it would be possible to use a custom world generator for new worlds and make them easily accessible to the users.

**Describe the solution you'd like**

I would like to either to have a static list of Custom World generators for users to choose from when creating a new world that should use a custom world generator or that the plugin automatically lists all available world generators for the user to choose from.

**Describe alternatives you've considered**

An alternative right now is to pre-create a world entry in the `bukkit.yml` file which means the server always has to be restarted when a (new) world that should use a custom world generator should be created.

**Additional context**

N/A

**Comment by einTosti** [comment]
Defiantly looking to add this in the future. Only problem is that is have no time at the moment due to my finals coming up very soon

**Comment by galexrt** [comment]
Thanks for the information! Good success with your finals.

**Comment by EinJOJO** [comment]
https://user-images.githubusercontent.com/62117829/126851196-a7431430-9fda-4784-b5d5-9b7d8588a6f3.mp4

So I tried to implement something like that. The Video has a Bitrate of 1000 because I cant uplaod files larger than 10mb  - so it's kind of full with pixels. 

But I guess you can roughly see it.

**Comment by einTosti** [comment]
Hey, 

your idea has been implemented in the latest update (v2.16).
Is this what you had in mind?

Have fun :D
