### ISSUE TITLE
`//undo` sometimes stops working when FAWE is used and world unloading is enabled

### ISSUE THREAD

**Issue by Schuwi** [einTosti/BuildSystem#91]
The issue is caused by FAWE but users of the BuildSystem should be aware and a workaround could be implemented in BuildSystem if the issue persists. See https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1671 for more information.

When using world unloading (`world.unload.enabled` true in config) it can happen that undo and redo sporadically stop working. The higher the unload delay and the more often players use worldedit the less likely this bug is to occur. Even when the conditions are "right" for this bug to occur (see the linked issue for steps to reproduce) it has a chance to just work instead because it depends on the Garbage Collector of the VM collecting the `org.bukkit.World`.

For a quick and (very) dirty workaround (which might work, kinda hard to test because of aforementioned reliance on the GC) see https://github.com/Schuwi/BuildSystem/tree/Schuwi/patch-we.

**Comment by Schuwi** [comment]
I just noticed my patch won't work if you /tp out of the world.

**Comment by einTosti** [comment]
Has been fixed by upstream
