### ISSUE TITLE
Empty generator

### ISSUE THREAD

**Issue by info65** [einTosti/BuildSystem#92]
Hi,
I have a problem. When I create a map using the EMPTY button, I have a FLAT platform around the map.

**Server information:**

- Minecraft version: 1.18.2.
- Server version Paper version git-Paper-267 (MC: 1.18.2)
- Plugin version 2.18.4

**Comment by einTosti** [comment]
Can replicate, however it seems to be a duplicate of #85

**Comment by einTosti** [comment]
Nvm, seems to be an issue with unloaded worlds
