### ISSUE TITLE
New menu bug

### ISSUE THREAD

**Issue by cb12438** [einTosti/BuildSystem#94]
If you use the 3d menu and you goto the close/cancel button and throw it you are un able to leave unless you leave the server then rejoin

The other bug:
If you have a freind online and you use the 3d menu if your freind right clicks the head they can take the head and make the menu unusable

**To Reproduce**

1. Activate the 3d menu
2. Go to the barrier then press q
3. 4. See error

2nd Bug steps:
1. Get a freind online
2. You open the 3d menu
3. Your freind right clicks a head on the 3d menu
4. You cant use the 3d menu as the head aint thier

**Expected behavior**
For you not to be able to throw the barrier so you can leave the menu

2nd Bug Behavoir:
For your frein not to be able to steal the head off the 3d menu

**Screenshots**
![image](https://user-images.githubusercontent.com/55159369/160903385-9cee21c9-5bbb-4342-abe2-5378787f3803.png)

**Server information:**

- Minecraft version: 1.18.2
- Server version Paper
- Plugin version 2.18.6

**Additional context**
Hope this can be fixed one day!

**Comment by einTosti** [comment]
I'll give this issue a low priority as it isn't completely game breaking, however I can understand it could be a bit annoying. Nevertheless, I'll eventually come around and fix this
