### ISSUE TITLE
GUI item give permission (I think is necesary)

### ISSUE THREAD

**Issue by Aitooor** [einTosti/BuildSystem#99]
**Is your feature request related to a problem? Please describe.**
I think you sould add permission node to the _/worlds item_ command

**Describe the solution you'd like**
It should be better for give the item only if you wanna give. And it don't have performance impact

I will add this here too:
<img width="457" alt="Captura de pantalla 2022-04-09 a las 2 48 59" src="https://user-images.githubusercontent.com/80640002/162550124-d8b39062-22aa-493c-87af-474cc7710152.png">

**Comment by einTosti** [comment]
Would you set it to the same permission which is needed to open the GUI? (`buildsystem.gui`)

**Comment by Aitooor** [comment]
Sure i have got limitated using that. But i thin is better to add the two permissions(to give the gratest impresion when you join the server without permissions to use the GUI)
